# Generated by Django 3.0.6 on 2020-05-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='anonymous', max_length=20)),
                ('birthday', models.DateField()),
                ('phonenumber', models.CharField(default='no number', max_length=20)),
                ('school', models.CharField(default='no school', max_length=20)),
                ('email', models.CharField(default='test@gmail.com', max_length=50)),
                ('address', models.CharField(default='address', max_length=60)),
                ('team', models.CharField(default='team', max_length=50)),
                ('auth', models.CharField(default='user', max_length=10)),
            ],
        ),
    ]
