# Generated by Django 3.0.6 on 2020-05-14 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_recurit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recurit',
            new_name='Recruit',
        ),
    ]
