# Generated by Django 3.0.6 on 2020-05-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20200514_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('contents', models.TextField(blank=True, max_length=500)),
                ('writer', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
