# Generated by Django 3.0.6 on 2020-05-16 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_edu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('writer', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='recruit',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.Comment'),
        ),
    ]
