# Generated by Django 3.0.6 on 2020-05-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_qna_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qna',
            name='comments',
        ),
        migrations.AddField(
            model_name='qna',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='comments', to='board.Comment'),
        ),
    ]
