# Generated by Django 3.0.6 on 2020-05-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20200516_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='qna_comments', to='board.Comment'),
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='comments',
        ),
        migrations.AddField(
            model_name='recruit',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='recruit_comments', to='board.Comment'),
        ),
    ]
