# Generated by Django 3.0.6 on 2020-05-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_recruit_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('team', models.CharField(max_length=50)),
                ('leader', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=10)),
                ('result', models.CharField(max_length=10)),
                ('writer', models.CharField(blank=True, max_length=50)),
                ('motivation', models.TextField(blank=True, max_length=500)),
                ('process', models.TextField(blank=True, max_length=500)),
                ('expectation', models.TextField(blank=True, max_length=500)),
                ('file', models.TextField(max_length=500)),
                ('comments', models.ManyToManyField(blank=True, related_name='mid_comments', to='board.Comment')),
            ],
        ),
    ]
