# Generated by Django 3.0.6 on 2020-05-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_mid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mid',
            name='writer',
            field=models.CharField(max_length=50),
        ),
    ]
