# Generated by Django 3.0.6 on 2020-05-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_auto_20200519_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('contents', models.TextField(blank=True, max_length=500)),
                ('attach', models.FileField(blank=True, null=True, upload_to='attach_file')),
            ],
        ),
    ]
