# Generated by Django 3.0.6 on 2020-05-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BM_Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('address', models.TextField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('accept', models.BooleanField()),
                ('idea_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SW_Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('address', models.TextField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('accept', models.BooleanField()),
                ('idea_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UX_Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('address', models.TextField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('accept', models.BooleanField()),
                ('idea_id', models.IntegerField()),
            ],
        ),
    ]
