# Generated by Django 3.0.6 on 2020-05-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_bm_voter_sw_voter_ux_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
