# Generated by Django 3.0.6 on 2020-05-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_fin_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fin',
            name='expectation',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='fin',
            name='motivation',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='fin',
            name='process',
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
