# Generated by Django 3.0.6 on 2020-05-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_auto_20200524_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fin',
            name='team',
            field=models.CharField(max_length=100),
        ),
    ]
